# Generated by Django 5.2.9 on 2026-05-26 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_alerta_leida_alerta_prioridad_and_more'),
        ('sensores', '0002_sensor_codigo_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='id_sensor',
            field=models.ForeignKey(blank=True, db_column='id_sensor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='sensores.sensor'),
        ),
    ]
