# Generated by Django 6.0.5 on 2026-06-25 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0004_alerta_atendida_id_finca'),
        ('cultivos', '0006_finca_estado_finca_tipo_cultivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='id_finca',
            field=models.ForeignKey(blank=True, db_column='id_finca', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='cultivos.finca'),
        ),
    ]
