# Generated by Django 5.2.9 on 2026-05-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='codigo_sensor',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
