# Generated by Django 6.0.5 on 2026-06-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0002_sensor_codigo_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='frecuencia_minutos',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='rango_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='rango_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='estado',
            field=models.CharField(default='Activo', max_length=50),
        ),
    ]
