# Generated by Django 5.2.9 on 2026-05-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0002_finca_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='nombre_cultivo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='tamaño_area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='ubicacion',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
