# Generated by Django 5.2.9 on 2026-06-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0004_finca_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
