# Generated by Django 6.0.5 on 2026-06-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0005_cultivo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='finca',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=50),
        ),
        migrations.AddField(
            model_name='finca',
            name='tipo_cultivo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
